<Project>
  <PropertyGroup>
    <Copyright>Copyright © 2013-2021 Akka.NET Project</Copyright>
    <Authors>Akka.NET Contrib</Authors>
    <VersionPrefix>1.6.0-beta3</VersionPrefix>
    <PackageIconUrl>http://getakka.net/images/akkalogo.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/akkadotnet/Akka.Persistence.MongoDB</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/master/LICENSE.md</PackageLicenseUrl>
    <PackageReleaseNotes>Built against Akka.NET 1.6.0-beta3.

* [Bump Akka.NET to 1.6.0-beta3](https://github.com/akkadotnet/akka.net/releases/tag/1.6.0-beta3)
* [Bump Akka.Hosting to 1.6.0-beta3](https://github.com/akkadotnet/akka.net/releases/tag/1.6.0-beta3)</PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>Akka Persistence journal and snapshot store backed by MongoDB database.</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <NetTestVersion>net10.0</NetTestVersion>
    <NetLibVersion>net10.0</NetLibVersion>
  </PropertyGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>