<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetStandardLibVersion);$(NetFrameworkLibVersion)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="reference.conf" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka.Persistence.Query" />
    <PackageReference Include="Akka.Streams" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Akka.Persistence.MongoDb.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
