# Pull request validation for Linux against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master

name: $(SourceBranchName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'net_8_tests_linux'
      displayName: '.NET 8 Unit Tests (Linux)'
      vmImage: 'ubuntu-latest'
      outputDirectory: 'bin/nuget'
      artifactName: 'nuget_pack-$(Build.BuildId)'
