# Pull request validation for Linux against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'net_core_tests_linux'
      displayName: '.NET Core Unit Tests (Linux)'
      vmImage: 'ubuntu-latest'
      scriptFileName: ./build.sh
      scriptArgs: runTestsNetCore

  - template: azure-pipeline.template.yaml
    parameters:
      name: 'net_7_tests_linux'
      displayName: '.NET 7 Unit Tests (Linux)'
      vmImage: 'ubuntu-latest'
      scriptFileName: ./build.sh
      scriptArgs: runTestsNet
