# Pull request validation for Windows against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'netfx_tests_windows'
      displayName: '.NET Framework Unit Tests (Windows)'
      vmImage: 'windows-latest'
      scriptFileName: build.cmd
      scriptArgs: runTests

  - template: azure-pipeline.template.yaml
    parameters:
      name: 'net_core_tests_windows'
      displayName: '.NET Core Unit Tests (Windows)'
      vmImage: 'windows-latest'
      scriptFileName: build.cmd
      scriptArgs: runTestsNetCore

  - template: azure-pipeline.template.yaml
    parameters:
      name: 'net_5_tests_windows'
      displayName: '.NET 5 Unit Tests (Windows)'
      vmImage: 'windows-latest'
      scriptFileName: build.cmd
      scriptArgs: runTestsNet

  - template: azure-pipeline.template.yaml
    parameters:
      name: 'nuget_pack'
      displayName: 'NuGet Pack'
      vmImage: 'windows-latest'
      scriptFileName: build.cmd
      scriptArgs: CreateNuget nugetprerelease=dev
      outputDirectory: 'bin/nuget'
      artifactName: 'nuget_pack-$(Build.BuildId)'
